name: Update Data Index

on:
  push:
    paths:
      - 'data/**'
      - '!data/index.json'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yq jq

      - name: Generate data index
        run: |
          cd data
          # Initialize JSON array
          echo -n '[' > index.json

          # Iterate through directories and parse frontmatter
          first=true
          for d in */; do
            # Check if README.md exists
            if [ -f "$d/README.md" ]; then
              # Extract frontmatter (between --- lines) and convert to JSON
              frontmatter=$(awk '/^---$/{if (p) exit; p=1; next}p' "$d/README.md" | yq eval -o=json)
              
              if [ ! -z "$frontmatter" ]; then
                # Add comma if not the first entry
                if [ "$first" = false ]; then
                  echo -n ',' >> index.json
                fi
                first=false

                # Add directory name and frontmatter to JSON
                echo -n "{\"directory\": \"${d%/}\", \"frontmatter\": $frontmatter}" >> index.json
              fi
            fi
          done

          # Close JSON array
          echo ']' >> index.json
          
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b update-index || git checkout update-index
          git add data/index.json
          git diff --staged --quiet || (git commit -m "Update data index with frontmatter" && git push origin update-index)
